---
- name: apply csf configs
  lineinfile:
    dest: "/etc/csf/csf.conf"
    regexp: "^{{ item.name }} ="
    line: '{{ item.name }} = "{{ item.config }}"'
  with_items: "{{ ((csf_global_conf | default([])) + (csf_conf | default([]))) |
                  items2dict(key_name='name', value_name='config') |
                  dict2items(key_name='name', value_name='config') }}"
  notify:
    - restart csf
    - restart lfd

# Uncomment some blocklists
- name: enable blocklists
  replace:
    dest: /etc/csf/csf.blocklists
    regexp: '^\#{{ item }}\|(\w+.*)?$'
    replace: '{{ item }}|\1'
  with_items: "{{ csf_blocklists|default([]) }}"
  when: csf_blocklists is defined
  notify:
    - restart csf
    - restart lfd

# add allowed ip to csf.allow
- name: csf - adding allowed ip
  lineinfile: >
    dest="/etc/csf/csf.allow"
    regexp="^{{ item }}"
    line="{{ item }}"
  with_items: "{{ csf_allow|default([]) }}"
  when: csf_allow is defined
  notify:
    - restart csf

# add ignored ip to csf.ignore
- name: csf - adding allowed ip
  lineinfile: >
    dest="/etc/csf/csf.ignore"
    regexp="^{{ item }}"
    line="{{ item }}"
  with_items: "{{ csf_ignore|default([]) }}"
  when: csf_ignore is defined
  notify:
    - restart csf
    - restart lfd
