---
# Tasks for CSF Configuration

# Include CSF install
- import_tasks: install.yml

# Include our allow includes
- import_tasks: includes.yml

# Include our configs
- import_tasks: configs.yml

# Whitelist Hosts
- import_tasks: whitelist.yml

# Whitelist DynDNS
- import_tasks: dyndns.yml
